# Generated by Django 4.2.30 on 2026-04-29 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("PasswordManager", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Credential",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("website_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("username", models.CharField(max_length=100)),
                ("password", models.CharField(max_length=255)),
                ("url", models.URLField()),
                ("logo", models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Note",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("headline", models.CharField(max_length=200)),
                ("bodytext", models.TextField()),
                (
                    "logo",
                    models.CharField(
                        default="manager/assets/NotesIcon.png", max_length=255
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(model_name="securednotes", name="owner",),
        migrations.DeleteModel(name="Credentials",),
        migrations.DeleteModel(name="SecuredNotes",),
    ]
