# Generated by Django 4.2.30 on 2026-05-15 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("PasswordManager", "0004_emergencyaccesscode"),
    ]

    operations = [
        migrations.RemoveField(model_name="recoverykey", name="created_at",),
        migrations.AddField(
            model_name="recoverykey",
            name="recovery_phrase_hash",
            field=models.CharField(default="placeholder", max_length=128),
            preserve_default=False,
        ),
    ]
